title: Hadi Borjkhani
logo: /assets/img/logo.png
description: 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
github:
  is_project_page: false
  repository_url: https://github.com/Hadi-Borjkhani/Projects_Hadi
  zip_url: # my CV
  tar_url: # may Proejcts link
  #repository_url: https://github.com/Hadi-Borjkhani/CV/blob/main/Hadi_Borjkhani_CV_Publications_Full.md
  Hadi: true
